### ISSUE TITLE
nwjs-vue boilerplate

### ISSUE THREAD

**Issue by ghost** [fritx/awesome-nw#3]
Hi
I've developed a complete NW.js & Vue.js boilerplate, I think it would be good if we add it to the list.
See it [here](https://github.com/elegantweb/nwjs-vue) please.

**Comment by TheJaredWilcurt** [comment]
Hey, I'm a big fan of both NW.js and Vue. So I'm excited about this, but couldn't get it to work, see:

https://github.com/elegantweb/nwjs-vue/issues/1

**Comment by ghost** [comment]
@TheJaredWilcurt Hi, I've answered you, thanks for the report.

**Comment by TheJaredWilcurt** [comment]
@sharifzadesina 

You have not fixed the issue (despite closing it).

Here's a recording on a different machine. Same problem occurs:

* https://youtu.be/XCyglPT10Ls

Also when tested on Ubuntu 16 32-Bit, it created a build for Linux 64-Bit (making it impossible to run or test the build on the platform that built it).

**Comment by ghost** [comment]
@TheJaredWilcurt Yes, you need to change build targets, see [here](https://github.com/elegantweb/nwjs-vue/blob/master/template/build/build.js#L65)

**Comment by TheJaredWilcurt** [comment]
That isn't mentioned in the documentation. It would make more sense to me to detect the user's OS/arch with `process.platform` and `process.arch` and then based on that build the appropriate versions. At least for the defaults. Or perhaps ask what platforms they wish to support during the setup, similar to asking what extra libraries to support (Vuex, Vue-router, etc).

**Comment by ghost** [comment]
@TheJaredWilcurt Yes, you are right, I will find best solution for this and will update it.

**Comment by TheJaredWilcurt** [comment]
Issue mentioned above is resolved, added to the list!
